# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2208f74ea39e178f90b5345261e244ea580e2680dde2d957ba21d6836f55db5955e6fa0eeefa980422bbf809057c3fd74d053183e1de26d397d40a50aad9b7

test:
  secret_key_base: ac05e6a05c71d72792f2db716c78057d378106c2f379a13b737e2a33bed117d275bb6f38741574444e06eb81242b1a8184fb69d9c4b53e0f3e32321459ab798d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
